[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
linker = "riscv64-unknown-none-elf-ld"

[profile.dev]
debug = true
opt-level = 0
lto = false

[profile.release]
debug = true
opt-level = 0
lto = true
