[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
linker = "riscv-none-eabi-ld"

[profile.dev]
debug = "full"
opt-level = 0
lto = false

[profile.release]
debug = 2
opt-level = "z"
lto = true
