[package]
name = "rust-xv6"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_xv6"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
buddy_system_allocator = "0.11.0"
talc = { version = "4.4.2", features = ["counters"], optional = true }
spin = "0.9.8"
fdt = "0.1.5"
zerocopy = { version = "0.8.5", default-features = false, features = ["derive"] }
virtio-drivers = "0.7.5"
attr-wrapper = { git = "https://github.com/nikitax44/attr-wrapper" }
# attr-wrapper = { path = "../../attr-wrapper" }
thiserror = { version = "2.0.0", default-features = false }
efs = "0.4.2"
log = "0.4.22"
critical-section = "1.2.0"
lock_api = "0.4.12"
