[package]
name = "rust-xv6"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_xv6"
crate-type = ["staticlib"]

[features]
default = []
talc = []

[dependencies]
buddy_system_allocator = "0.11.0"
talc = { version = "4.4.2", features = ["counters"] }
spin = "0.9.8"
fdt = "0.1.5"
zerocopy = { version = "0.8.5", default-features = false, features = ["derive"] }
virtio-drivers = "0.7.5"
riscv = { version = "0.11.1", features = ["s-mode"] }
bitflags = "2.6.0"
attr-wrapper = { git = "https://github.com/nikitax44/attr-wrapper" }
thiserror = { version = "2.0.0", default-features = false }
efs = { git = "https://codeberg.org/RatCornu/efs" }
log = "0.4.22"
critical-section = "1.2.0"
